### ISSUE TITLE
How to handle idl import inside another idl

### ISSUE THREAD

**Issue by youyuanwu** [riverar/washington-rs#1]
Hi riverar.
I have A.idl and B.idl, and B.idl imports A.idl.
How to generate rust modules A and B, such that B reuses/references code in A?
I tried this:
```
<ItemGroup>
        <Idls Include="A.idl" />
        <Partition Include="A.cpp">
            <TraverseFiles>$(CompiledHeadersDir)\A.h</TraverseFiles>
            <Namespace>Microsoft.A</Namespace>
        </Partition>
        <Idls Include="B.idl" />
        <Partition Include="B.cpp">
            <TraverseFiles>$(CompiledHeadersDir)\B.h</TraverseFiles>
            <TraverseFiles>$(CompiledHeadersDir)\A.h</TraverseFiles>
            <Namespace>Microsoft.B</Namespace>
        </Partition>
    </ItemGroup>
```
Which produces duplicated A.idl rust code in B module again, instead of reusing/referencing it from module A.

Let me know if this is possible.

**Comment by riverar** [comment]
Hey @youyuanwu, I just updated this repository ([d62b9b3](https://github.com/riverar/washington-rs/commit/d62b9b3687fad967fb48f4c9b1d7fe1983aa08d6)).

`<Idls>` is an [input item](https://docs.microsoft.com/visualstudio/msbuild/msbuild-items) pointing to one or more IDLs, to be passed to the MIDL compiler via the [`CompileIdls` task](https://github.com/microsoft/win32metadata/blob/main/sources/GeneratorSdk/MetadataTasks/CompileIdls.cs).

Example:
```xml
<ItemGroup>
    <Idls Include="A.idl;B.idl;C.idl" />
</ItemGroup>
```

After the `CompileIdls` task completes, the `$(CompiledHeadersDir)` location will contain usable headers. Those can be selected and partitioned as needed.

Example:
```xml
<ItemGroup>
    <Idls Include="idl\washington.idl;idl\state.idl" />
    <Partition Include="state.cpp">
        <TraverseFiles>$(CompiledHeadersDir)\state.h</TraverseFiles>
        <Namespace>Microsoft.States</Namespace>
    </Partition>
    <Partition Include="washington.cpp">
        <TraverseFiles>$(CompiledHeadersDir)\washington.h</TraverseFiles>
        <Namespace>Microsoft.States.Washington</Namespace>
    </Partition>
</ItemGroup>
```

Does that help?

**Comment by youyuanwu** [comment]
Thanks. This works.

Further question:
* Is it possible to make the namespace parallel to each other? For your example I want Microsoft.States and Microsoft.Washington, and they are not nested.
* Is it possible to condense 2 or more idls into one namespace? I tried to do it but got exceptions: "The process cannot access the file xxx because it is being used by another process."

Improvements:
Document this step:
* `dotnet tool install --global ClangSharpPInvokeGenerator --version 14.0.0-beta1`
It is not installed on my system by default and took me a while to figure out.
* In crates/tools/api/src/main.rs the "write_toml" function has
```
[dependencies.windows]
version = "0.38"
```
It should be version 0.37 the same in the "crates\tools\api\Cargo.toml" file, otherwise the generated code might not compile, since windows-bindgen might spit out code that only compiles with the same version. The other way to resolve is to update the tools_api code to use 0.38.

**Comment by riverar** [comment]
> Is it possible to make the namespace parallel to each other? For your example I want Microsoft.States and Microsoft.Washington, and they are not nested.

Yep.

```diff
<ItemGroup>
    <Idls Include="idl\washington.idl;idl\state.idl" />
    <Partition Include="state.cpp">
        <TraverseFiles>$(CompiledHeadersDir)\state.h</TraverseFiles>
        <Namespace>Microsoft.States</Namespace>
    </Partition>
    <Partition Include="washington.cpp">
        <TraverseFiles>$(CompiledHeadersDir)\washington.h</TraverseFiles>
-       <Namespace>Microsoft.States.Washington</Namespace>
+       <Namespace>Microsoft.Washington</Namespace>
    </Partition>
</ItemGroup>
```

Produces:
![image](https://user-images.githubusercontent.com/475132/177674601-fc246bbf-94d0-4095-bd9b-701d3e007d28.png)

---

> Is it possible to condense 2 or more idls into one namespace? I tried to do it but got exceptions: "The process cannot access the file xxx because it is being used by another process."

Yep.

```cpp
// combined.cpp
#include <state.h>
#include <washington.h>
```

```diff
<ItemGroup>
    <Idls Include="idl\washington.idl;idl\state.idl" />
-   <Partition Include="state.cpp">
+   <Partition Include="combined.cpp">
-       <TraverseFiles>$(CompiledHeadersDir)\state.h;</TraverseFiles>
+       <TraverseFiles>$(CompiledHeadersDir)\state.h;$(CompiledHeadersDir)\washington.h</TraverseFiles>
-       <Namespace>Microsoft.States</Namespace>
+       <Namespace>Microsoft.Combined</Namespace>
    </Partition>
-   <Partition Include="washington.cpp">
-       <TraverseFiles>$(CompiledHeadersDir)\washington.h</TraverseFiles>
-      <Namespace>Microsoft.States.Washington</Namespace>
-   </Partition>
-</ItemGroup>
```

Produces:
![image](https://user-images.githubusercontent.com/475132/177674860-75504368-64ee-41a5-9d05-dd8e271c0725.png)

**Comment by youyuanwu** [comment]
There are some class undefined/missing errors when trying to get 2 idl in the same namespace or parallel namespace mentioned above for my complex idls. The washington example in this repo works fine.
But the namespace problem is not blocking what I am doing other than the generated code layout is not optimal.

Once I have more time to work on this, I will give a small repo.

The original issue that this issue is targeted for is resolved, so closing this.

**Comment by riverar** [comment]
@youyuanwu If you'd like to share more details  under NDA feel free to reach out privately or via Kenny.

**Comment by youyuanwu** [comment]
@riverar  I will reach out. This is a side project that I am experimenting with. I work on this slowly and I am sure there are more problems to come.
