### ISSUE TITLE
Can we achieve the same for Csharp?

### ISSUE THREAD

**Issue by youyuanwu** [riverar/washington-rs#5]
Reading from CsWinRT repo and CsWin32 repo, it seems possible to generate csharp binding from winmd file.
Is there an example repo for doing this? Maybe it can be added to this repo as well.

Maybe related to https://github.com/microsoft/CsWin32/issues/356

**Comment by riverar** [comment]
@youyuanwu If you add `<ProjectionMetadataWinmd Include="$(MSBuildProjectDirectory)\path\to\your.winmd" />` to your C# project, it should work great. I use this a lot, no issues aside from the one you linked above.

cc: @aarnott for awareness

**Comment by youyuanwu** [comment]
@riverar I don't seem to be able to get this to work. Can give me a simple example?

**Comment by AArnott** [comment]
You'll also need to reference the CsWin32 package:

```xml
<ItemGroup>
   <ProjectionMetadataWinmd Include="$(MSBuildProjectDirectory)\path\to\your.winmd" />
</ItemGroup>
<ItemGroup>
   <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.18-beta" PrivateAssets="all" />
</ItemGroup>
```

Then add a `NativeMethods.txt` file to your project directory and start naming APIs to generate that are defined in your winmd file. CsWin32 should generate them the same way it generates from win32metadata.

Please review the README file at the https://github.com/Microsoft/CsWin32 repo for more details.
